version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - terraformImage="hashicorp/terraform:0.14.11"
      - docker pull $terraformImage
      - echo 'AWS_ACCESS_KEY_ID="$AWS_KEY"'> .env
      - echo 'AWS_SECRET_ACCESS_KEY="$AWS_SECRET"' >>.env
      - echo 'AWS_REGION=us-east-1' >> .env
      - echo 'AWS_OUTPUT=json'>> .env
      - echo 'TFVAR_PROJ_NAME="$PROJECT_NAME"'>> .env
      - echo 'TFVAR_VPC_ID="$VPC_ID"' >> .env
  pre_build:
    commands:
      - login=$(aws ecr get-login --region=us-east-1)
      - login=$(echo $login | sed 's/-e none/ /g' | tee)
      - echo $login | bash      
  build:
    commands:
      - dockerterraform="docker run --rm -w /app  -v $PWD/deploy:/app --env-file=.env $terraformImage"
      - $dockerterraform init 
      - $dockerterraform workspace select $CODEBUILD_WEBHOOK_HEAD_REF || $dockerterraform workspace new $CODEBUILD_WEBHOOK_HEAD_REF
      - $dockerterraform destroy  -auto-approve
      - $dockerterraform plan  -out plan.out
      - $dockerterraform apply  -auto-approve
      - elb=$($dockerterraform output elb_public)
      - echo $elb >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt
    - plan.out