version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - terraformImage="hashicorp/terraform:0.14.11"
      - docker pull $terraformImage
      - echo 'TFVAR_PROJ_NAME="$PROJECT_NAME"'> .env
      - echo 'TFVAR_VPC_ID="$VPC_ID"' >> .env
      - mkdir .aws && echo $AWS_CREDENTIALS > .aws/credentials
  pre_build:
    commands:
      - login=$(aws ecr get-login --region=us-east-1)
      - login=$(echo $login | sed 's/-e none/ /g' | tee)
      - echo $login | bash      
  build:
    commands:
      - dockerterraform="docker run --rm -w /app  -v $PWD:/app -v $PWD/.aws:/root/.aws -e --env-file=.env $terraformImage"
      - $dockerterraform init 
      - $dockerterraform workspace select $STAGE || $dockerterraform workspace new $STAGE
      - $dockerterraform destroy  -auto-approve
      - $dockerterraform plan  -out plan.out
      - $dockerterraform apply  -auto-approve
      - elb=$($dockerterraform output elb_public)
      - echo $elb >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt
    - plan.out