version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq wget unzip
      - wget https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
      - unzip terraform_0.14.11_linux_amd64.zip
  pre_build:
    commands:
    #  - login=$(aws ecr get-login --region=us-east-1)
    #  - login=$(echo $login | sed 's/-e none/ /g' | tee)
    #  - echo $login | bash      
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_KEY
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET
      - export AWS_REGION=us-east-1
      - export AWS_OUTPUT=json
      - export TF_VAR_PROJECT_NAME=$PROJECT_NAME
      - export TF_VAR_VPC_ID=$VPC_ID
      - export BRANCH=main
      - cd deploy
      - ../terraform init 
      - ../terraform workspace select $BRANCH || ../terraform workspace new $BRANCH
      - ../terraform destroy -auto-approve
#      - ../terraform plan  -out plan.out
#      - ../terraform apply  -auto-approve
#      - elb=$(../terraform output elb_public)
#      - echo $elb >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    